kernel: ltq-vdsl-vr9-mei: fix compilation warning
Fix simple compilation warning due to cast and wrong include.
Fix compilation warning:
In file included from ./include/linux/compat.h:18,
                 from ./include/linux/filter.h:10,
                 from ./include/net/sock.h:59,
                 from /home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/drv_mei_cpe-1.5.17.6/src/drv_mei_cpe_linux.c:70:
./include/uapi/linux/aio_abi.h:77:45: error: "__LITTLE_ENDIAN" is not defined, evaluates to 0 [-Werror=undef]
   77 | #if defined(__BYTE_ORDER) ? __BYTE_ORDER == __LITTLE_ENDIAN : defined(__LITTLE_ENDIAN)
      |                                             ^~~~~~~~~~~~~~~
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/drv_mei_cpe-1.5.17.6/src/drv_mei_cpe_linux.c: In function 'MEI_MeminfoProcPerDevGet':
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/drv_mei_cpe-1.5.17.6/src/drv_mei_cpe_linux.c:1715:56: error: format '%X' expects argument of type 'unsigned int', but argument 4 has type 'IFX_uint8_t *' {aka 'unsigned char *'} [-Werror=format=]
 1715 |                seq_printf(s, "chunk[%02d]: addr = 0x%08X (0x%08X), "
      |                                                     ~~~^
      |                                                        |
      |                                                        unsigned int
      |                                                     %08hhn
......
 1721 |                      chunkIdx, pChunk[chunkIdx].pImageChunk_aligned,
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                |
      |                                                IFX_uint8_t * {aka unsigned char *}
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/drv_mei_cpe-1.5.17.6/src/drv_mei_cpe_linux.c:1715:64: error: format '%X' expects argument of type 'unsigned int', but argument 5 has type 'IFX_uint8_t *' {aka 'unsigned char *'} [-Werror=format=]
 1715 |                seq_printf(s, "chunk[%02d]: addr = 0x%08X (0x%08X), "
      |                                                             ~~~^
      |                                                                |
      |                                                                unsigned int
      |                                                             %08hhn
......
 1722 |                      pChunk[chunkIdx].pImageChunk_allocated,
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      |
      |                                      IFX_uint8_t * {aka unsigned char *}
cc1: all warnings being treated as errors

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>