ath79: 5.15: drop unused res variable from pci ar71xx OF convert patch
Drop unused res variable from pci ar71xx OF convert patch fixing
compilation warning:

arch/mips/pci/pci-ar71xx.c: In function 'ar71xx_pci_probe':
arch/mips/pci/pci-ar71xx.c:287:26: error: unused variable 'res' [-Werror=unused-variable]
  287 |         struct resource *res;
      |                          ^~~
cc1: all warnings being treated as errors

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>