layerscape: port "-Werror" fix from NXP tree
At this moment, 702-phy-Add-2.5G-SGMII-interface-mode.patch cause error
durring kernel compilation:

  CC      drivers/net/phy/phylink.o
drivers/net/phy/phylink.c: In function 'phylink_get_capabilities':
drivers/net/phy/phylink.c:443:9: error: enumeration value 'PHY_INTERFACE_MODE_2500SGMII' not handled in switch [-Werror=switch]
  443 |         switch (interface) {
      |         ^~~~~~
cc1: all warnings being treated as errors

NXP take care of it. Let's port their patch.

Signed-off-by: Pawel Dembicki <paweldembicki@gmail.com>